
language: go
sudo: false
go: 
 - 1.8.x
 - 1.9.x
 - 1.10.x

notificaitons:
  email:
    recipients: danielfireman@gmail.com
    on_success: change
    on_failure: always

before_install:
  - go get github.com/mattn/goveralls

script:
 - $HOME/gopath/bin/goveralls -service=travis-ci -ignore=examples/infer/main.go,examples/validate/main.go
